### PR TITLE
Update KeyModifier.java

### PR DESCRIPTION
**Pull request by ElucGeek**
Bitcoin symbol added.

### CODE REVIEW

**Comment by ElucGeek** [comment]
OK I removed from the new layout, we can leave as it is in the KeyModifier.

**Comment by ElucGeek** [comment]
Sorry should not have closed it I guess.

**Comment by Julow** [comment]
Have you pushed the changes to the layout to the same branch as https://github.com/Julow/Unexpected-Keyboard/pull/390 ?
This PR have been merged so you need to commit your changes on the branch of this PR (`master-1`).

**Comment by Julow** [comment]
I want to release soon so I'll take care of editing.

**Pull request merged**
