### PR TITLE
Added Czech translation and layout

### PR DESCRIPTION
**Pull request by Validbit**
Translated keyboard and created Czech multilingual "practical" layout for faster typing and typing in commonly used languages (German, Slovak + French w/accents)

_I've designed the layout to be more useful and practical in typing while preserving QWERTZ and certain alphanumeric symbols (PC keyboard) where change wasn't needed/available_

I've tested it (and made changes) for a week. I plan on using it for a long time so feel free to modify or ask for help or changing commits.
_Thank you for this amazing gift of a keyboard to us all. Hope you're doing well._

### CODE REVIEW

**Review by Julow — APPROVED** [review]
Amazing, thanks a lot !

I leave it open in case you need to make a change to the layout, I'll merge before the next release or when you say it's ready.

**Comment by Validbit** [comment]
When do you (roughly) plan to release a new version?  (So I can "finalize" changes from feedback/usage in one commit)

**Comment by Julow** [comment]
Hi! Sorry for the late reply. I would like to release this weekend :)

**Comment by Julow** [comment]
I'll merge now but please feel free to make new PRs in the future, even for tiny changes.

**Pull request merged**
