### PR TITLE
Change the place of چ  and ژ in Persian Keyboard Layout

### PR DESCRIPTION
**Pull request by Danger-Mkh**
#749

### CODE REVIEW

**Review by Julow — APPROVED** [review]
Thanks!

@RZHSSNZDH Do you approve ?

**Comment by RZHSSNZDH** [comment]
> Thanks!
> 
> @RZHSSNZDH Do you approve ?

It is fine, but I think switching the places of `.` and `ژ` will be better.
Thank you @Danger-Mkh!

**Comment by Danger-Mkh** [comment]
> It is fine, but I think switching the places of `.` and `ژ` will be better.

I think the place of `.` is good because it remains consist.
@RZHSSNZDH

**Comment by Danger-Mkh** [comment]
I think we're ready to merge.

What do you think @Julow ?

**Comment by Julow** [comment]
Thanks !

**Pull request merged**
