### PR TITLE
Circle and round trip gestures

### PR DESCRIPTION
**Pull request by Julow**
This implements clockwise/anticlockwise circle and round trip gestures inspired by Messagease.

The circle gestures start after a small threshold to avoid making the regular swipe too hard to aim.

The gestures do:

- clockwise circle: Shift variant of the center symbol
- anticlockwise circle: Fn variant of the center symbol
- round trip: Fn variant of the targetted side symbol

### CODE REVIEW

**Comment by Spike-from-NH** [comment]
Almost makes the SHIFT key unnecessary! I dabbled with the round-trip gesture but triggered auto-repeat. Should I get more proficient or experiment with the timings in settings? or should you disable auto-repeat for swipes?

**Comment by Julow** [comment]
Thanks for the quick feedback!

> in messageease-like layouts most of the letters are on the side keys and not on the center keys. therefore, uppercase is only more accessible for a few center keys, because fn is applied for the round trip gesture. for these layouts it might be more convenient to apply shift for the round trip gesture.

Good point!
I changed the clockwise circle and the round trip gesture to apply Shift with a fallback on Fn if that did nothing.
The anticlockwise circle now does nothing but I intent to make it configurable in layouts.

> I dabbled with the round-trip gesture but triggered auto-repeat

The round trip is intended to be a short and quick swipe then back to the center. Do you have a very short repeat time ?
The circles are also intended to be small: less than 1/5 of a turn.

> I noticed that gestures are always applied to the basic key, no matter if this key is currently shown. for example: press Fn and the a-key becomes æ. next do the shift gesture on æ. I would expect to get Æ, i.e. the same as when shift ane fn are both activated without gestures. but the shift gesture on æ results in an A. is this intentional?

That's fixed, thanks!

For the reversing, I'll leave that for an other time to not delay the release too much.
It remains that the gesture do not work well with intermediate characters in compose sequences but that'll also be for later.

**Comment by Julow** [comment]
Many thanks for the feedback :) I'll merge as-is and leave updating the video and the other improvements to possibly before next release but more likely after.

**Comment by Moini** [comment]
@Julow Hi! I helped someone install unexpected keyboard on their new phone this afternoon, and we were wildly guessing what 'circle gesture sensitivity' meant, and found no documentation in the F-Droid store or in the app itself. 

This bug report here seems to be the only place where it is explained - but only with reference to another program that we do not have installed. 

Could this please be documented in the description or with a tooltip or something in the settings? I'm still not sure how to invoke 'round trip gesture', no idea what that means. A video would be nice.

**Comment by Spike-from-NH** [comment]
A round-trip gesture is when you swipe away from a key but then swipe back to the key before lifting your finger. A subheading in the Settings menu would be a good place to make it clearer. @Julow has talked about adding multimedia to the menu in the future.

**Comment by Julow** [comment]
A video or rather some animated vector graphics, would be the best way to document this and other features. I don't have a lot of knowledge on that subject and I would appreciate help :)

**Comment by Moini** [comment]
How would it need to be animated? CSS, SMIL or JS? What size? Are there restrictions on the subset of SVG features?

**Comment by Moini** [comment]
> A round-trip gesture is when you swipe away from a key but then swipe back to the key before lifting your finger. A subheading in the Settings menu would be a good place to make it clearer. @Julow has talked about adding multimedia to the menu in the future.

Thank you!

**Comment by Julow** [comment]
@Moini I don't know what kind of animated graphics are supported by Android but my guess is that there is a lot of restrictions. They also have their [own format](https://developer.android.com/develop/ui/views/animations/drawable-animation).
I've tried including a video into the app before but making a single video file that will play on most devices is hopeless.
Sorry, I don't have the time to look at this currently.

**Comment by ChiefMikeK** [comment]
@Moini  
<details>
<summary>How to insert [xml] text file to Github</summary>

### Code Block

add three back ticks+syntax 
Needs a blank line ↓ whitespace after this! ↓↓↓↓↓↓↓↓↓↓↓

```xml
<animated-vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt">
    <aapt:attr name="android:drawable">
        <vector
            android:name="vector"
            android:width="136dp"
            android:height="136dp"
            android:viewportWidth="136"
            android:viewportHeight="136">
            <path
                android:name="path"
                android:pathData="M 54.162 16.247 L 82.079 16.247 C 84.33 16.247 86.542 16.84 88.492 17.965 C 90.441 19.091 92.061 20.71 93.186 22.66 C 94.312 24.61 94.905 26.822 94.905 29.073 L 94.905 56.989 C 94.905 59.241 94.312 61.453 93.186 63.402 C 92.061 65.352 90.441 66.971 88.492 68.097 C 86.542 69.223 84.33 69.815 82.079 69.815 L 54.162 69.815 C 50.762 69.815 47.497 68.463 45.093 66.059 C 42.688 63.654 41.336 60.39 41.336 56.989 L 41.336 29.073 C 41.336 25.673 42.688 22.408 45.093 20.004 C 47.497 17.599 50.762 16.247 54.162 16.247"
                android:fillColor="#808080"
                android:strokeWidth="1"/>
            <path
                android:name="path_1"
                android:pathData="M 72.358 59.407 L 65.979 48.593 L 63.309 50.447 L 63.309 59.407 L 57.107 59.407 L 57.107 26.655 L 63.309 26.655 L 63.309 45.415 L 71.828 35.527 L 78.493 35.527 L 70.107 44.841 L 79.133 59.407 Z"
                android:fillColor="#b3b3b3"
                android:strokeWidth="1"/>
            <group
                android:name="group"
                android:translateX="-23.792161542818434"
                android:translateY="33.59804680518174">
                <path
                    android:name="path_2"
                    android:pathData="M 66.34 36.217 C 64.522 36.211 62.748 36.782 61.275 37.849 C 59.801 38.915 58.704 40.421 58.141 42.15 C 57.578 43.879 57.578 45.743 58.141 47.472 C 58.704 49.201 59.801 50.708 61.275 51.774 C 62.748 52.84 64.522 53.411 66.34 53.406 C 68.619 53.406 70.806 52.5 72.418 50.888 C 74.029 49.277 74.935 47.09 74.935 44.811 C 74.935 42.533 74.029 40.345 72.418 38.734 C 70.806 37.123 68.619 36.217 66.34 36.217 Z"
                    android:fillColor="#ffffff"
                    android:fillAlpha="0.5"
                    android:strokeAlpha="0"
                    android:strokeLineCap="round"
                    android:strokeLineJoin="round"/>
                <path
                    android:name="path_3"
                    android:pathData="M 71.777 98.395 C 73.458 91.591 67.229 90.66 67.229 90.66 C 67.229 90.66 71.321 87.242 67.898 82.832 C 65.662 79.952 61.409 80.705 61.409 80.705 C 61.409 80.705 63.364 77.348 60.541 74.558 C 57.269 71.323 52.779 72.76 52.779 72.76 C 52.779 72.76 56.416 66.63 58.531 64.128 C 60.024 62.364 61.928 59.323 68.593 49.893 C 73.372 43.132 65.778 38.102 60.213 44.007 C 55.506 49.005 41.826 69.057 40.342 70.992 C 39.327 72.323 34.954 79.063 32.566 77.815 C 31.641 76.477 33.671 67.032 31.806 60.814 C 30.224 55.542 24.991 54.188 23.712 56.281 C 23.039 57.382 24.411 68.759 19.191 77.843 C 15.668 83.977 20.511 100.006 21.012 102.728 C 18.476 106.069 15.596 110.424 14.291 112.896 C 18.508 121.489 26.032 126.633 36.563 128.639 C 37.607 126.581 40.313 122.757 43.78 118.921 C 43.78 118.921 55.573 116.325 63.02 110.214 C 66.979 106.965 70.095 105.199 71.777 98.395 Z"
                    android:fillColor="#808080"
                    android:strokeColor="#000000"
                    android:strokeWidth="1"
                    android:strokeLineCap="square"/>
            </group>
        </vector>
    </aapt:attr>
    <target android:name="group">
        <aapt:attr name="android:animation">
            <set>
                <objectAnimator
                    android:propertyName="translateX"
                    android:duration="1035"
                    android:valueFrom="-23.792161542818434"
                    android:valueTo="0"
                    android:valueType="floatType"
                    android:interpolator="@android:anim/accelerate_decelerate_interpolator"/>
                <objectAnimator
                    android:propertyName="translateY"
                    android:duration="1035"
                    android:valueFrom="33.59804680518174"
                    android:valueTo="0"
                    android:valueType="floatType"
                    android:interpolator="@android:anim/accelerate_decelerate_interpolator"/>
                <objectAnimator
                    android:propertyName="translateX"
                    android:startOffset="1302"
                    android:duration="1198"
                    android:valueFrom="0"
                    android:valueTo="-23.792161542818434"
                    android:valueType="floatType"
                    android:interpolator="@android:interpolator/fast_out_slow_in"/>
                <objectAnimator
                    android:propertyName="translateY"
                    android:startOffset="1302"
                    android:duration="1198"
                    android:valueFrom="0"
                    android:valueTo="33.59804680518174"
                    android:valueType="floatType"
                    android:interpolator="@android:interpolator/fast_out_slow_in"/>
            </set>
        </aapt:attr>
    </target>
    <target android:name="path_2">
        <aapt:attr name="android:animation">
            <set>
                <objectAnimator
                    android:propertyName="fillAlpha"
                    android:duration="1127"
                    android:valueFrom="0"
                    android:valueTo="0"
                    android:valueType="floatType"
                    android:interpolator="@android:interpolator/fast_out_slow_in"/>
                <objectAnimator
                    android:propertyName="fillAlpha"
                    android:startOffset="1127"
                    android:duration="81"
                    android:valueFrom="0"
                    android:valueTo="0.6"
                    android:valueType="floatType"
                    android:interpolator="@android:interpolator/fast_out_slow_in"/>
            </set>
        </aapt:attr>
    </target>
</animated-vector>

```
</details>

**Comment by Moini** [comment]
Thanks, but that wasn't what I wanted to do.

**Comment by Julow** [comment]
@Moini That works! Which editor have you used ?

**Pull request merged**
