### PR TITLE
Modify persian layout and add some new characters

### PR DESCRIPTION
**Pull request by RZHSSNZDH**
- Add character `پ` and `ژ`
- Change math operators and symbols location

### CODE REVIEW

**Comment by RZHSSNZDH** [comment]
Using persian layout without merging this PR is almost impossible.

**Comment by RZHSSNZDH** [comment]
`Make Apk CI` failed again. Can you help me more?

**Comment by vladgba** [comment]
```
Error: Color value not valid -- must be #rgb, #argb, #rrggbb, or #aarrggbb (at 'key2' with value '#').
```
Damn, the hashtag also needs to be escaped. I hope that's all.

P.S. you can see for yourself what error occurs by clicking "details"

**Comment by Julow** [comment]
Here's how the layout looks now:
shot

Have you been able to try it on your phone ? You can find the latest build of your PR here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/4960624038?pr=348

**Comment by RZHSSNZDH** [comment]
Thanks. I did not see any problem.

**Comment by RZHSSNZDH** [comment]
I forgot `.`! I added it. I did not any other problem.

**Comment by RZHSSNZDH** [comment]
> Here's how the layout looks now: shot
> 
> Have you been able to try it on your phone ? You can find the latest build of your PR here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/4960624038?pr=348

Im my layout I did not add and do not see most of characters which there are in your screenshot. For example in "م" char, only there is a ")" in up left, but in your picture there is another char in right down. Also when I installed the debug apk I did not see such thing in my phone.

**Review by Julow — APPROVED** [review]
I'll merge. Feel free to open new PRs to make further changes.

**Pull request merged**
