### PR TITLE
Some changes in characters' positions in persian.xml

### PR DESCRIPTION
**Pull request by RZHSSNZDH**
Changes some characters' places like `!`.

### CODE REVIEW

**Comment by RZHSSNZDH** [comment]
I am not an android app developer, so I do not have installed its tools, so make commands to add the layout does not work and I get error below:
`Makefile:46: *** ANDROID_HOME not set.  Stop.`

**Review by Julow — COMMENTED** [review]
What do you think of modifying the existing layout instead ? I'd prefer one well-maintained by several people rather than several slightly different layouts.

**Comment by RZHSSNZDH** [comment]
> What do you think of modifying the existing layout instead ? I'd prefer one well-maintained by several people rather than several slightly different layouts.

You are right, but when I clone the project, I could not find `persian.xml` in `/res/xml`. So I created a new persian xml file.

**Comment by Julow** [comment]
Layouts have all been renamed to `<script>_<layout name>_<country>`, Persian is now `/res/xml/arab_pc_ir.xml`.

**Pull request closed without merging**
