### PR TITLE
Added tamil layout

### PR DESCRIPTION
**Pull request by ms-jagadeeshan**
Added a tamil layout. The layout looks better with 0.8 scale. Is there any way to it automatically when selecting keyboard?
One more question, is there any way to add transliteration layout?
Thank you very much for creating this project, i have been using unexpected keyboard from its first release.

### CODE REVIEW

**Comment by ms-jagadeeshan** [comment]
okay, this layout have all dependent and independent forms.

**Review by Julow — APPROVED** [review]
Awesome, thanks! The layout looks very nice.

**Comment by Julow** [comment]
> The layout looks better with 0.8 scale. Is there any way to it automatically when selecting keyboard?

You mean the size of the symbols ? There's several ways but I think doing that globally in `KeyValue` is the one that will require the less amount of maintenance. I've implemented it and pushed to your branch, what do you think ?

> One more question, is there any way to add transliteration layout?

Like for the numpad for example ? No this is not possible currently. What would be yur use case ?

**Comment by ms-jagadeeshan** [comment]
> You mean the size of the symbols ? There's several ways but I think doing that globally in `KeyValue` is the one that will require the less amount of maintenance. I've implemented it and pushed to your branch, what do you think ?

yeah i meant the symbol size, now the letters look better

> Like for the numpad for example ? No this is not possible currently. What would be yur use case ?

Transliteration layout i mean, generating tamil text from english , for example a becomes அ , aa becomes ஆ , ka becomes க etc

**Comment by Julow** [comment]
Transliteration is not possible currently. Would you be interested in implementing it ?

**Review by Julow — APPROVED** [review]
Thanks for this nice contribution, let's merge!

I pushed to your branch to resolve the conflicts and some other changes.

**Comment by ms-jagadeeshan** [comment]
Yeah, I am interested to implement, i will gothrough how other keyboards implement and you could also guide me with the approach and resources.

**Pull request merged**
