### PR TITLE
Georgian layouts added

### PR DESCRIPTION
**Pull request by Kxeo**
Decided to make some layouts for Georgian, because it definitely doesn't seem like this app has any.

### CODE REVIEW

**Comment by Kxeo** [comment]
Whoops. I forgot layouts.xml. Well it was not so much as forgetting than not knowing how to edit it. I'm on a tablet rn.

**Review by Julow — APPROVED** [review]
Thanks!

Don't worry about `layouts.xml`, it's generated automatically. I pushed to your branch.

The layouts contain every ASCII punctuation symbols. Are they useful ? If they are, only `` ` `` is missing.

I'll merge if you confirm it's as intended.

**Comment by Kxeo** [comment]
> The layouts contain every ASCII punctuation symbols. Are they useful ?
Well, definitely, if you consider Armenian useful. I based both of them off the EN-US QWERTY layout.
>  If they are, only `` ` `` is missing.
Screenshot_20241204-155146
Whoops. That shoulsn't be up there. Gonna have to fix that fast.
`<key key0="ნ" key1="ჼ" key2="`" key3=":" key4=";"/>`
There. Now all is right in the world.

**Comment by Julow** [comment]
> Well, definitely, if you consider Armenian useful.

Sorry, my question was, are ASCII punctuation symbols like `[]{}$~`, etc.. useful ? I guess yes as you added the missing `` ` ``.

I've pushed your change, I'll merge.

**Pull request merged**
