### PR TITLE
Hindi minor update

### PR DESCRIPTION
**Pull request by lrvideckis**

### CODE REVIEW

**Comment by lrvideckis** [comment]
On second thought, Let's keep the `,` and `;` even though they are seldom used (but not never) in Hindi.

I use the `*` to correct the previous text
I use the `@` to link someone's name in What'sapp

**Review by Julow — APPROVED** [review]
Thanks!

**Comment by JonathanAlexMasc** [comment]
@lrvideckis नटखट

**Comment by lrvideckis** [comment]
@JonathanAlexMasc तु सही हो कि मैं एक नटखट लड़का हूँ

**Pull request merged**
