### PR TITLE
Complete /res/values-fa/strings.xml translation

### PR DESCRIPTION
**Pull request by RZHSSNZDH**

### CODE REVIEW

**Review by Julow — APPROVED** [review]
Many thanks!

**Comment by RZHSSNZDH** [comment]
> Many thanks!

When will you release it?

**Comment by Julow** [comment]
The next release is not planned before 2 weeks from now. You can download the latest apk here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/4779432671
Is that OK for you ?

**Comment by RZHSSNZDH** [comment]
> The next release is not planned before 2 weeks from now. You can download the latest apk here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/4779432671 Is that OK for you ?

Sorry! I am not android apps developer, so I do not have the requirenments (SDK and etc) to build the app.

**Comment by Julow** [comment]
Are you able to install the debug apk ? (link is near the bottom of the page)

**Comment by RZHSSNZDH** [comment]
> Are you able to install the debug apk ? (link is near the bottom of the page)

It has some problems. I try to repait them until tomorrow.

**Pull request merged**
