### PR TITLE
Update symbols from unicode to font-Icon

### PR DESCRIPTION
**Pull request by sdrapha**
This PR fixes issue #79 

Currently some of the symbols don't render consistently across different devices because they are unicode symbols, which render unpredictably with different phone's system fonts.

I'm updating them to use font-icons that I added in the included embed font from this keyboard

So the Emoji and Settings Cog will always render consistently,
also once I was already adding icons, I updated the Home, End, PageUp and PageDown too, to better represent them
image

### CODE REVIEW

**Comment by ChiefMikeK** [comment]
could you increase the contrast and post a screen shot here 🤔 as i've suggested here?

https://github.com/Julow/Unexpected-Keyboard/issues/78#issue-1150599968

**Comment by sdrapha** [comment]
> could you increase the contrast and post a screen shot here 🤔 as i've suggested here?
> 
> [#78 (comment)](https://github.com/Julow/Unexpected-Keyboard/issues/78#issue-1150599968)

that is something else. You are talking about color themes. This PR doesn't touch any theme definition at all, it's separate from that.

**Comment by ChiefMikeK** [comment]
And sorry to bother you but, several dead keys render poorly  
https://github.com/Julow/Unexpected-Keyboard/blob/7b04048c3e951027bf186c56790c8d3cddc55742/srcs/juloo.keyboard2/KeyValue.java#L162
macron

**Comment by ChiefMikeK** [comment]
> > could you increase the contrast and post a screen shot here 🤔 as i've suggested here?
> > [#78 (comment)](https://github.com/Julow/Unexpected-Keyboard/issues/78#issue-1150599968)
> 
> that is something else. You are talking about color themes. This PR doesn't touch any theme definition at all, it's separate from that.

ok I would fix myself but me internet is very poor here

**Comment by sdrapha** [comment]
That I agree. Same thing I'm doing in this PR could be done for more icons. 
That could be done later, following the same scheme. Of course if @Julow agreeing to all these changes.
I won't have time to change this myself right now. 
Maybe I could try helping with that later. 
I basically used FontForge software to edit the .ttf
You can also check the current font-icons in the .ttf using VSCode with the fonts extension installed. 
For the Home and End symbols, I created them entirely in FontForge. Also, there are some websites that can provide some free licensed font-icons like Fontenello and Icomoon. I used some from them, copy and pasted the specific icon from their .ttf into this keyboard .ttf using FontForge, and fixed the size proportions and position to match the existing ones.

**Comment by Julow** [comment]
Thanks a lot ! The glyphs you chose look very nice. It's generally good practice to credit the original author of such things (and sometimes mandated by the license), where do they come exactly ?

Many other glyphs need to be improved and I planned to do that eventually. Editing the font file manually is not ideal and I'm looking at other solutions, that's why it's taking so much time. On the long term, I'd like the font file to be reproducibly built from text descriptions like svg, or not using a font at all.

**Comment by Julow** [comment]
Thanks. I've added that to a README.

**Pull request merged**
